services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# services:
#   db:
#     container_name: postgres
#     image: postgres:17-alpine
#     environment:
#       POSTGRES_USER: 'postgres'
#       POSTGRES_PASSWORD: 'postgres'
#       POSTGRES_DB: 'ny_taxi'
#     ports:
#       - '5433:5432'
#     volumes:
#       - vol-pgdata:/var/lib/postgresql/data

#   pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4:latest
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
#       PGADMIN_DEFAULT_PASSWORD: "pgadmin"
#     ports:
#       - "8080:80"
#     volumes:
#       - vol-pgadmin_data:/var/lib/pgadmin  

# volumes:
#   vol-pgdata:
#     name: vol-pgdata
#   vol-pgadmin_data:
#     name: vol-pgadmin_data